/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiOpenaiChatRouteImport } from './routes/api/openai/chat'
import { Route as ApiOpenaiModelsRouteImport } from './routes/api/openai/models'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenaiChatRoute = ApiOpenaiChatRouteImport.update({
  id: '/api/openai/chat',
  path: '/api/openai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenaiModelsRoute = ApiOpenaiModelsRouteImport.update({
  id: '/api/openai/models',
  path: '/api/openai/models',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/openai/chat': typeof ApiOpenaiChatRoute
  '/api/openai/models': typeof ApiOpenaiModelsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/openai/chat': typeof ApiOpenaiChatRoute
  '/api/openai/models': typeof ApiOpenaiModelsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/openai/chat': typeof ApiOpenaiChatRoute
  '/api/openai/models': typeof ApiOpenaiModelsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/openai/chat' | '/api/openai/models'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/openai/chat' | '/api/openai/models'
  id: '__root__' | '/' | '/api/openai/chat' | '/api/openai/models'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiOpenaiChatRoute: typeof ApiOpenaiChatRoute
  ApiOpenaiModelsRoute: typeof ApiOpenaiModelsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openai/chat': {
      id: '/api/openai/chat'
      path: '/api/openai/chat'
      fullPath: '/api/openai/chat'
      preLoaderRoute: typeof ApiOpenaiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openai/models': {
      id: '/api/openai/models'
      path: '/api/openai/models'
      fullPath: '/api/openai/models'
      preLoaderRoute: typeof ApiOpenaiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiOpenaiChatRoute: ApiOpenaiChatRoute,
  ApiOpenaiModelsRoute: ApiOpenaiModelsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
