/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiXaiChatRouteImport } from './routes/api/xai/chat'
import { Route as ApiXaiModelsRouteImport } from './routes/api/xai/models'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiXaiChatRoute = ApiXaiChatRouteImport.update({
  id: '/api/xai/chat',
  path: '/api/xai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiXaiModelsRoute = ApiXaiModelsRouteImport.update({
  id: '/api/xai/models',
  path: '/api/xai/models',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/xai/chat': typeof ApiXaiChatRoute
  '/api/xai/models': typeof ApiXaiModelsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/xai/chat': typeof ApiXaiChatRoute
  '/api/xai/models': typeof ApiXaiModelsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/xai/chat': typeof ApiXaiChatRoute
  '/api/xai/models': typeof ApiXaiModelsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/xai/chat' | '/api/xai/models'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/xai/chat' | '/api/xai/models'
  id: '__root__' | '/' | '/api/xai/chat' | '/api/xai/models'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiXaiChatRoute: typeof ApiXaiChatRoute
  ApiXaiModelsRoute: typeof ApiXaiModelsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/xai/chat': {
      id: '/api/xai/chat'
      path: '/api/xai/chat'
      fullPath: '/api/xai/chat'
      preLoaderRoute: typeof ApiXaiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/xai/models': {
      id: '/api/xai/models'
      path: '/api/xai/models'
      fullPath: '/api/xai/models'
      preLoaderRoute: typeof ApiXaiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiXaiChatRoute: ApiXaiChatRoute,
  ApiXaiModelsRoute: ApiXaiModelsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
